
USE GDP_project_db

--CREATE THE TABLE

IF OBJECT_ID('Raw_Data_GDP') IS NOT NULL DROP TABLE Raw_Data_GDP

CREATE TABLE Raw_Data_GDP 
( DEMO_IND NVARCHAR(200), 
  INDICATOR NVARCHAR(200),
  [LOCATION] NVARCHAR(200),
  COUNTRY NVARCHAR(200),
  [TIME] NVARCHAR(200),
  [VALUE] FLOAT,
  [FLAG CODES] NVARCHAR(200),
  FLAGS NVARCHAR(200)
  )

-- IMPORT RAW DATA

BULK INSERT Raw_Data_GDP
FROM 'C:\Users\natac\OneDrive\Desktop\GDP-Analysis-Dashboard\gdp_raw_data.csv'
WITH (FORMAT ='CSV')

--SELECT * FROM Raw_Data_GDP

--SELECT DISTINCT INDICATOR FROM Raw_Data_GDP

--CREATE VIEW
CREATE VIEW GDP_SELECTED_INPUT AS

SELECT a.*, b.GDP_Per_Capita FROM

	(SELECT COUNTRY, [TIME] AS Year_No, [VALUE] AS GDP_Value FROM Raw_Data_GDP
	 WHERE INDICATOR = 'GDP (current US$)') a

	 LEFT JOIN
	 (SELECT COUNTRY, [TIME] AS Year_No, [value] AS GDP_Per_Capita FROM Raw_Data_GDP
	 WHERE INDICATOR = 'GDP per capita (current US$)' ) b
	 ON a.COUNTRY = b.COUNTRY AND a.Year_No = b.Year_No

--SELECT * FROM  GDP_SELECTED_INPUT


--STORED PROCEDURE
CREATE PROCEDURE GDP_INPUT_MONTHLY AS

IF OBJECT_ID('Raw_Data_GDP') IS NOT NULL DROP TABLE Raw_Data_GDP

CREATE TABLE Raw_Data_GDP 
( DEMO_IND NVARCHAR(200), 
  INDICATOR NVARCHAR(200),
  [LOCATION] NVARCHAR(200),
  COUNTRY NVARCHAR(200),
  [TIME] NVARCHAR(200),
  [VALUE] FLOAT,
  [FLAG CODES] NVARCHAR(200),
  FLAGS NVARCHAR(200)
  )

BULK INSERT Raw_Data_GDP
FROM 'C:\Users\natac\OneDrive\Desktop\GDP-Analysis-Dashboard\gdp_raw_data.csv'
WITH (FORMAT ='CSV')

--EXEC GDP_INPUT_MONTHLY







